#Configuration for failfast=false

info:
  component: Turbine
  
# HTTP Server
server:
  port: 8989
  
management:
  port: -1
  security:
    enabled: false

turbine:
  clusterNameExpression: new String("CYGNUS")
  aggregator:
    clusterConfig: CYGNUS
  appConfig: DENEB
  InstanceMonitor.eventStream.skipLineLogic.enabled: false
  
  
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    
 
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'
    org.springframework.integration: DEBUG

