# HTTP Server
server:
  port: ${PORT:9999}

# App info
info:
  app:
    name: @project.artifactId@
    description: @project.description@
      
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
     preferIpAddress: true
