# HTTP Server
server:
  port: ${ADMIN_SERVER_PORT:9999}

      
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
     preferIpAddress: true
     
management:
  security:
    enabled: false
