# HTTP Server
server:
  port: 9999
      
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
     preferIpAddress: true
     
management:
  security:
    enabled: false
