#Configuration for failfast=false

# HTTP Server
server:
  port: ${PORT:3333}

# App info
info:
  app:
    name: @project.artifactId@
    description: @project.description@

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.atsistemas: 'DEBUG'

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

cygnus:
  deneb:
    name: deneb
    pingUrl: http://${cygnus.deneb.name}/ping/

spring:
   rabbitmq:
     host: rabbitmq
     port: 5672
     username: guest
     password: guest