swagger: '2.0'
info:
  version: 0.1-SNAPSHOT
  title: Cygnus - Sadr
  description: |
basePath: /sadr   
paths:
  /ping:
    get:
      responses:
        200:
          description: Response from Sadr
          schema:
            $ref: '#/definitions/PingResponse'
      
definitions:
  PingResponse:
    type: object
    required:
      - id
    properties:
      id:
        type: string
      responseMessage:
        type: string