#Configuration for failfast=false

# HTTP Server
server:
  port: 2222

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    org.springframework.web: 'DEBUG'
    com.atsistemas: 'DEBUG'

management:
  security:
    enabled: false
    
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

cygnus:
  sadr:
    name: sadr
    pingUrl: http://${cygnus.sadr.name}/ping/

spring:
   rabbitmq:
     host: rabbitmq
     port: 5672
     username: guest
     password: guest        
                
      
     
