swagger: '2.0'
info:
  version: 0.1-SNAPSHOT
  title: Cygnus - Deneb

basePath: /deneb  
paths:
  '/ping':
    get:
      parameters:
      - name: forwardService
        in: query
        description: service name to forward ping
        type: string
        required: false
      responses:
        200:
          description: Response from Deneb
          schema:
            $ref: '#/definitions/PingResponse'
        404:
          description: Not found
      
definitions:
  PingResponse:
    type: object
    required:
      - id
    properties:
      id:
        type: string
      responseMessage:
        type: string