version: '3'
services:

  config-server:
    image: ${GROUP_ID}/config-server
    container_name: config-server
    ports:
      - "8888:${DEFAULT_PORT}"
    environment:
      DEFAULT_PORT: ${DEFAULT_PORT}
      SPRING_PROFILES_ACTIVE: ${CONFIG_SERVER_SPRING_PROFILES_ACTIVE}
      CONFIG_REPO: ${CONFIG_REPO}
      LOCAL_CONFIG_REPO: ${LOCAL_CONFIG_REPO}
    depends_on:
      - rabbitmq
    volumes:
      - ${LOCAL_CONFIG_REPO}:/cygnus-config

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"

  eureka:
    image: ${GROUP_ID}/eureka
    container_name: eureka
    ports:
      - "1111:${DEFAULT_PORT}"
    environment:
      DEFAULT_PORT: ${DEFAULT_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      CONFIG_SERVER_ENDPOINT: ${CONFIG_SERVER_ENDPOINT}
      CONFIG_RETRY_INITIAL_INTERVAL: ${CONFIG_RETRY_INITIAL_INTERVAL}
    depends_on:
      - config-server
  
  sadr:
    image: ${GROUP_ID}/sadr
    container_name: sadr
    ports:
      - "3333:${DEFAULT_PORT}"
    environment:
      DEFAULT_PORT: ${DEFAULT_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      CONFIG_SERVER_ENDPOINT: ${CONFIG_SERVER_ENDPOINT}
      CONFIG_RETRY_INITIAL_INTERVAL: ${CONFIG_RETRY_INITIAL_INTERVAL}
      EUREKA_ENDPOINT: ${EUREKA_ENDPOINT}
    depends_on:
      - config-server
      - eureka
      - rabbitmq

      
      