version: '3'

services:

  config-server:
    image: config-server
    container_name: config-server
    ports:
      - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
    environment:
      - CONFIG_SERVER_PORT=${CONFIG_SERVER_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - CONFIG_REPO=file:/cygnus-config
    depends_on:
      - rabbitmq
    volumes:
      - ${CONFIG_SERVER_REPO}:/cygnus-config

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"

  eureka-server:
    image: eureka-server
    container_name: eureka-server
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - EUREKA_SERVER_PORT=${EUREKA_SERVER_PORT}
      - CONFIG_SERVER_ENDPOINT=${CONFIG_SERVER_ENDPOINT}
      - CONFIG_RETRY_INITIAL_INTERVAL=${CONFIG_RETRY_INITIAL_INTERVAL}
    depends_on:
      - config-server
  
  admin-server:
    image: admin-server
    container_name: admin-server
    ports:
      - "${ADMIN_SERVER_PORT}:${ADMIN_SERVER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - ADMIN_SERVER_PORT=${ADMIN_SERVER_PORT}
      - CONFIG_SERVER_ENDPOINT=${CONFIG_SERVER_ENDPOINT}
      - CONFIG_RETRY_INITIAL_INTERVAL=${CONFIG_RETRY_INITIAL_INTERVAL}
      - EUREKA_ENDPOINT=${EUREKA_ENDPOINT}
    depends_on:
      - config-server
      - eureka-server
  
  hystrix-dashboard:
    image: hystrix-dashboard
    container_name: hystrix-dashboard
    ports:
      - "${HYSTRIX_DASHBOARD_PORT}:${HYSTRIX_DASHBOARD_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - HYSTRIX_DASHBOARD_PORT=${HYSTRIX_DASHBOARD_PORT}
      - CONFIG_SERVER_ENDPOINT=${CONFIG_SERVER_ENDPOINT}
      - CONFIG_RETRY_INITIAL_INTERVAL=${CONFIG_RETRY_INITIAL_INTERVAL}
    depends_on:
      - config-server
      - eureka-server
      - sadr
      - deneb
  
  turbine:
    image: turbine
    container_name: turbine
    ports:
      - "${TURBINE_PORT}:${TURBINE_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - TURBINE_PORT=${TURBINE_PORT}
      - CONFIG_SERVER_ENDPOINT=${CONFIG_SERVER_ENDPOINT}
      - CONFIG_RETRY_INITIAL_INTERVAL=${CONFIG_RETRY_INITIAL_INTERVAL}
    depends_on:
      - config-server
      - eureka-server
      - sadr
      - deneb
      
  sadr:
    image: sadr
    container_name: sadr
    ports:
      - "3333:3333"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - CONFIG_SERVER_ENDPOINT=${CONFIG_SERVER_ENDPOINT}
      - CONFIG_RETRY_INITIAL_INTERVAL=${CONFIG_RETRY_INITIAL_INTERVAL}
      - EUREKA_ENDPOINT=${EUREKA_ENDPOINT}
    depends_on:
      - config-server
      - eureka-server
       - rabbitmq
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      
  deneb:
    image: deneb
    container_name: deneb
    ports:
      - "2222:2222"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - CONFIG_SERVER_ENDPOINT=${CONFIG_SERVER_ENDPOINT}
      - CONFIG_RETRY_INITIAL_INTERVAL=${CONFIG_RETRY_INITIAL_INTERVAL}
      - EUREKA_ENDPOINT=${EUREKA_ENDPOINT}
    depends_on:
      - config-server
      - eureka-server
      - rabbitmq
      - sadr

  zuul-proxy:
    image: zuul-proxy
    container_name: zuul-proxy
    ports:
      - "${ZUUL_PORT}:${ZUUL_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - ZUUL_PORT=${ZUUL_PORT}
      - CONFIG_SERVER_ENDPOINT=${CONFIG_SERVER_ENDPOINT}
      - CONFIG_RETRY_INITIAL_INTERVAL=${CONFIG_RETRY_INITIAL_INTERVAL}
      - EUREKA_ENDPOINT=${EUREKA_ENDPOINT}
    depends_on:
      - config-server
      - eureka-server
      - sadr
      - deneb
      - admin-server
      - hystrix-dashboard
  
      
  