version: '3'
services:

  config-server:
    image: ${GROUP_ID}/config-server
    container_name: config-server
    ports:
      - "8888:${DEFAULT_PORT}"
    environment:
      DEFAULT_PORT: ${DEFAULT_PORT}
      SPRING_PROFILES_ACTIVE: ${CONFIG_SERVER_SPRING_PROFILES_ACTIVE}
      CONFIG_REPO: ${CONFIG_REPO}
      LOCAL_CONFIG_REPO: ${LOCAL_CONFIG_REPO}
    depends_on:
      - rabbitmq
    volumes:
      - ${LOCAL_CONFIG_REPO}:/cygnus-config

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"

