version: '2'
services:

  config-server:
    image: config-server
    container_name: config-server
    ports:
      - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
    environment:
      - CONFIG_SERVER_PORT=${CONFIG_SERVER_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - LOCAL_CONFIG_REPO_PATH=file:/cygnus-config
    depends_on:
      - rabbitmq
    volumes:
      - ${LOCAL_CONFIG_REPO_PATH}:/cygnus-config

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"

  eureka-server:
    image: eureka-server
    container_name: eureka-server
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - EUREKA_SERVER_PORT=${EUREKA_SERVER_PORT}
      - CONFIG_SERVER_ENDPOINT=${CONFIG_SERVER_ENDPOINT}
      - CONFIG_RETRY_INITIAL_INTERVAL=${CONFIG_RETRY_INITIAL_INTERVAL}
    depends_on:
      - config-server
