server:
  port: ${DEFAULT_PORT:8888}

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'

management:
  security:
    enabled: false
    
spring:
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    
---    
spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO}
          default-label: develop
          searchPaths:
          - local
          - docker

---
spring:
  profiles: local-repo
  cloud:
    config:
      server:
        git:
          uri: file:///cygnus-config
          default-label: develop
          searchPaths:
          - local
          - docker
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          searchLocations: file://${LOCAL_CONFIG_REPO}/{profile}
