server:
  port: ${PORT:8888}
  
logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'
        
spring:
  application:
    name: configserver  # Service registers under this name
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: file:///D:/development/cygnus-config
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/atSistemas/cygnus-config
#         uri: file:///${HOME}/cygnus-config
