server:
  port: ${CONFIG_SERVER_PORT:8888}

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'

management:
  security:
    enabled: false
    
spring:
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    
---    
spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO}
          default-label: develop

#---
#spring:
#  profiles: native
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: file:/media/dani/Data/workspaces/STS/cygnus-config/{profile}

---
spring:
  profiles: local
  cloud:
    config:
      server:
        git:
          uri: file:/${HOME}/git/cygnus-config
          searchPaths:
          - dev
